name: p4templates - scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    name: MEND scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

    - name: Login to docker hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f #v4.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up JDK
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 #v6.0.1
      with:
        distribution: temurin
        java-version: '25'
    - run: java --version

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0
      with:
        python-version: '3.13'
    - run: python my_script.py

    # TODO update docker pull
    - name: Mend scan
      run: |
        echo resolveAllDependencies=False > ${{ github.workspace }}/MEND.config
        echo python.resolveDependencies=True >> ${{ github.workspace }}/MEND.config
        echo python.path=python3 >> MEND.config
        docker pull perforce/ubuntu22-mend
        docker run -v ${{ github.workspace }}:/scan \
        perforce/ubuntu22-mend bash -c "
        java -jar /opt/white-source/wss-unified-agent.jar \
        -c /scan/MEND.config \
        -d /scan \
        -project p4templates-main \
        -product p4templates \
        -apiKey ${{ secrets.MEND_API_KEY }} \
        -userKey ${{ secrets.MEND_USER_KEY }} \
        -wss.url ${{ secrets.MEND_URL }}"
